name: cicd_test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      -main


jobs:
  build:
    runs-on: ubuntu-latest

    steps :
    - uses : actions/checkout@v2

    - name: build oreumi test
      run: pip install -r requirements.txt

    - name: build
      run: python app.py
      
    - name: test
      run: python app.py test
      
    - name: deploy
      run: python app.py prod
